version: '3.3'
services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile
    ports:
      - "8000:8000"
    
  
      # ${FAST_API_APPLICATION_PORT}